### ISSUE TITLE
CUDA example compilation issue

### ISSUE THREAD

**Issue by pavlo-iuriichuk** [cleuton/golang-network#2]
Could you please fix the issue in the [README](https://github.com/cleuton/golang-network/blob/master/english/cuda/nostress/README.md), when I tried to run `go run maxmul.go` I observed error `/tmp/go-build3332526432/b001/exe/maxmul: error while loading shared libraries: libmaxmul.so: cannot open shared object file: No such file or directory`. I had to add `LD_LIBRARY_PATH=$PWD go run maxmul.go` to make it work.

This issue might be related: https://stackoverflow.com/questions/51283102/cgo-ignores-the-ldflags-l-option-on-macos

If you wish I could create a pull request with a comment.

**Comment by cleuton** [comment]
please create a pull request

Em qua., 29 de dez. de 2021 23:02, Pavlo Iuriichuk ***@***.***>
escreveu:

**Comment by pavlo-iuriichuk** [comment]
@cleuton See: https://github.com/cleuton/golang-network/pull/3

I used google translate for the Portuguese text, feel free to edit it as a native speaker.
